import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { cn } from "@/helper/cn";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";

import { auth } from "@/helper/auth";
import Header from "@/components/header";
import Footer from "@/components/footer";
import DialogCreateAuction from "./(main)/components/dialog-create-auction";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Carties",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDevelopment = process.env.NODE_ENV === "development";

  return (
    <html lang="en">
      <body
        className={cn(
          fontSans.variable,
          clsx({ "debug-screens": isDevelopment }),
          "font-sans",
        )}
      >
        <Providers>{children}</Providers>
        <Toaster duration={4000} />
      </body>
    </html>
  );
}
