import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { cn } from "@/helper/cn";
import Providers from "./providers";

import { auth } from "@/helper/auth";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Carties",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDevelopment = process.env.NODE_ENV === "development";
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          clsx({ "debug-screens": isDevelopment }),
          "bg-slate-50",
        )}
      >
        <Providers>
          <div className="mb-8 shadow-sm">
            <Header user={session?.user} />
          </div>
          <div className="mx-auto mb-8 max-w-screen-xl px-4 sm:px-6 lg:px-8">
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
